unstable_features = true

max_width = 140
indent_style = "Block"
reorder_imports = true
brace_style = "PreferSameLine"
chain_width = 140
combine_control_expr = false
comment_width = 140
control_brace_style = "AlwaysSameLine"
fn_call_width = 140
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
doc_comment_code_block_width = 140